def alternatingCharacters(s):
    ar = []
    for char in s:
        ar.append(char)
    index = 0
    while True:
        while True:
            if ar[index] == 'A':
                if ar[index + 1] == 'A':
                    ar[index + 1] = 0
                    ar.remove(0)
                    break
                else:
                    index += 1
            elif ar[index] == 'B':
                if ar[index + 1] == 'B':
                    ar[index + 1] = 0
                    ar.remove(0)
                    break
                else:
                    index += 1
            if index+1 == len(ar):
                break
        if index+1 == len(ar):
            break

    return len(s)-len(ar)


print(alternatingCharacters('BABABBBBBABBABBBAAABBBBBBBBABBBBBABBBAABBBBABBBBBBBAABABBBBBBABBABBBBBBBBBABBBBBABBABBBBABABBBBBBBBBBBBBBBBBBBABBBBBAABABBBBBBBBBBBABABBBABBBABBBBBBBBBBABBBBBABBBABBBABBABBBBBBAABBBABABBBAABABAABBBBAABBBBBBBBBAAABBABABBABBBABBBBABBBBBABABBBBABABBBAABBABBAABBBBBBABBABBBBBBBBBBBBBBBBBABBBBBBABBBBBBBBABBABBBBBBBBBAAABBBBBBBBBABBABABBBAAABBBBBBABBABBBBBBBABBBBBABBBABBAABAABAAABABBBBBBBABBBBABBBBBABBBBBBABBABBBBBBBBBBBBBBBBBABBABBBAABBBBBAABABBBBBBAABBBBBBBBBABBBBBABBABBBBBBBBBABBBBBBABBBABBBBBABBBBBBBBBBBBBBBBBBABBBBBBBBBBABBBBABABBBBBBBBABBBBBBBBBABBBBBAAABBBBABABABBBBABBBBBBBBBBAABBBBBBBBABBAABBBBBBBBBABAABBBBBBBBBBBBABBBBABABBBBBBBBABBBBBBBBBBBBABBBBABBBBBABBBBBBBBBBABBAABBBABBBBBBBBBABBBBAABBBBBBBBABABABBBBBABBBBBBBBBBBBBBBBBBABBBBABBBBBABBABABAABBBABBBBBBBBBAABABABBBBBBBBAABBBBABBABBBABBBBAABBABABBBBABAABBBBBBBBBBABBABBBBBABAABBBBBBBBBBBBABABBBBBBBBBBABAABABBBBABBBBBBBBBBBBBABBBBBABBABBAABBBBABBBBBBBBBBBAABBBBBBBBBBBBBBAABABBBBBABBBBBBBBBABBBBABBBBABABBABBBBABABBBABABAAABBBBAAAAAABBBA'))